#S3 서버에서 EC2로 프로젝트 파일이 오고 실행되는 파일

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/step3/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:

  AfterInstall:
    - location: stop.sh # 엔진엑스에 연결되어 있지 않은 스프링부트 종료
      timeout: 60
      runas: root

  ApplicationStart:
    - location: start.sh # 엔진엑스에 연결되어 있지 않은 port에 새 버전 스프링부트 프로젝트 실행
      timeout: 60
      runas: root

  ValidateService:
    - location: health.sh # 실행 정상인지 체크
      timeout: 60
      runas: root